s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow
  outflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/outflow
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: fcre
  name: Falling Creek Reservoir
  latitude: 37.307
  longitude: -79.837
da_setup:
  da_method: enkf
  par_fit_method: inflate
  ensemble_size: 31
  localization_distance: 2
  pf_always_resample: no
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: no
  use_inflation_factor: yes
  inflation_factor: 1.08
  inflation_only_at_da: yes
  add_random_noise: no
model_settings:
  ncore: 10
  max_model_layers: 75
  model_name: glm
  base_GLM_nml: glm3_fcre.nml
  modeled_depths:
  - 0.0
  - 1.0
  - 1.5
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  par_config_file: parameter_calibration_config_fcre.csv
  obs_config_file: observations_config_fcre.csv
  states_config_file: states_config_fcre.csv
default_init:
  lake_depth: 9.4
  temp:
  - 25.667
  - 24.9101
  - 23.067
  - 21.8815
  - 19.6658
  - 16.5739
  - 12.9292
  - 12.8456
  - 12.8127
  - 12.8079
  - 12.778
  temp_depths:
  - 0.127
  - 1.004
  - 2.005
  - 3.021
  - 4.002
  - 5.004
  - 6.004
  - 7.01
  - 8.001
  - 9.015
  - 9.518
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
  include_inflow: yes
  include_outflow: yes
  future_inflow_model: future/model_id=historical_interp
  historical_inflow_model: historical/model_id=historical_interp
  local_inflow_directory: drivers/inflow
  future_outflow_model: future/model_id=historical_interp
  historical_outflow_model: historical/model_id=historical_interp
  local_outflow_directory: drivers/outflow
  use_ler_vars: no
  use_flows_s3: no
met:
  future_met_model: gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}
  future_met_use_s3: no
  historical_met_use_s3: no
  forecast_lag_days: 0
  historical_met_model: gefs-v12/stage3/site_id={site_id}
  local_met_directory: drivers/met
  use_ler_vars: no
  use_openmeteo: no
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  inflow: yes
output_settings:
  diagnostics_names: extc
