s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow
  outflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/outflow
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: ccre
  name: Carvins Cove Reservoir
  latitude: 37.3697
  longitude: -79.958
da_setup:
  da_method: enkf
  par_fit_method: inflate
  ensemble_size: 31
  localization_distance: 2
  pf_always_resample: no
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: no
  use_inflation_factor: yes
  inflation_factor: 1.08
  inflation_only_at_da: yes
  add_random_noise: no
model_settings:
  ncore: 10
  max_model_layers: 75
  model_name: glm
  base_GLM_nml: glm3_ccre.nml
  modeled_depths:
  - 0.0
  - 0.25
  - 0.5
  - 0.75
  - 1.0
  - 1.25
  - 1.5
  - 1.75
  - 2.0
  - 2.25
  - 2.5
  - 2.75
  - 3.0
  - 3.25
  - 3.5
  - 3.75
  - 4.0
  - 4.25
  - 4.5
  - 4.75
  - 5.0
  - 5.25
  - 5.5
  - 5.75
  - 6.0
  - 6.25
  - 6.5
  - 6.75
  - 7.0
  - 7.25
  - 7.5
  - 7.75
  - 8.0
  - 8.25
  - 8.5
  - 8.75
  - 9.0
  - 9.25
  - 9.5
  - 9.75
  - 10.0
  - 10.25
  - 10.5
  - 10.75
  - 11.0
  - 11.25
  - 11.5
  - 11.75
  - 12.0
  - 12.25
  - 12.5
  - 12.75
  - 13.0
  - 13.25
  - 13.5
  - 13.75
  - 14.0
  - 14.25
  - 14.5
  - 14.75
  - 15.0
  - 15.25
  - 15.5
  - 15.75
  - 16.0
  - 16.25
  - 16.5
  - 16.75
  - 17.0
  - 17.25
  - 17.5
  - 17.75
  - 18.0
  - 18.25
  - 18.5
  - 18.75
  - 19.0
  - 19.25
  - 19.5
  - 19.75
  - 20.0
  - 20.25
  - 20.5
  - 20.75
  - 21.0
  par_config_file: parameter_calibration_config_ccre.csv
  obs_config_file: observations_config_ccre.csv
  states_config_file: states_config_ccre.csv
default_init:
  lake_depth: 22.8
  temp:
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  temp_depths:
  - 0.1
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  - 10.0
  - 11.0
  - 15.0
  - 19.0
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
  include_inflow: no
  include_outflow: no
  future_inflow_model: NA
  historical_inflow_model: NA
  local_inflow_directory: drivers/inflow
  future_outflow_model: future/model_id=historical_interp
  historical_outflow_model: historical/model_id=historical_interp
  local_outflow_directory: drivers/outflow
  use_ler_vars: no
  use_flows_s3: no
met:
  future_met_model: gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}
  future_met_use_s3: no
  historical_met_use_s3: no
  forecast_lag_days: 0
  historical_met_model: gefs-v12/stage3/site_id={site_id}
  local_met_directory: drivers/met
  use_ler_vars: no
  use_openmeteo: no
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  inflow: yes
output_settings:
  diagnostics_names: extc
