s3:
  drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/sunp/lm_ar
  outflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/sunp/lm_ar
  targets:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: sunp
  name: Lake Sunapee
  latitude: 43.3913
  longitude: 72.0576
metadata:
  generate_eml: yes
  forecast_project_id: test
  abstract: This is where a longer description of the forest can be added
  forecast_title: FLARE
  intellectualRights: insert license
  model_description:
    forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
    name: General Lake Model
    type: process-based
    repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
  me:
    individualName:
      givenName: Whitney
      surName: Woelmer
    electronicMailAddress: wwoelmer@vt.edu
    id: INSERT ORCID
da_setup:
  da_method: enkf
  par_fit_method: perturb_const
  ensemble_size: 200
  localization_distance: .na
  no_negative_states: yes
  assimilate_first_step: no
  inflation_factor: 1.08
  use_obs_constraint: yes
model_settings:
  ncore: 4
  model_name: glm3
  base_GLM_nml: glm3_sunp.nml
  modeled_depths:
  - 0.1
  - 0.5
  - 1.0
  - 1.5
  - 2.0
  - 3.0
  - 3.5
  - 4.0
  - 4.5
  - 5.0
  - 5.5
  - 6.0
  - 6.5
  - 7.0
  - 7.5
  - 8.0
  - 8.5
  - 9.0
  - 9.5
  - 10.0
  - 15.0
  - 20.0
  - 25.0
  - 30.0
  max_model_layers: 100
  par_config_file: parameter_calibration_config_sunp.csv
  obs_config_file: observations_config_sunp.csv
  states_config_file: states_config_sunp.csv
default_init:
  lake_depth: 33
  temp:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  temp_depths:
  - 0.127
  - 1.004
  - 2.005
  - 3.021
  - 4.002
  - 5.004
  - 6.004
  - 7.01
  - 8.001
  - 9.015
  - 9.518
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
  include_inflow: no
  include_outflow: no
  use_forecasted_inflow: no
  forecast_inflow_model: NA
  observed_inflow_filename: NA
  inflow_variables: NA
  use_ler_vars: no
  historical_inflow_model: NA
  future_inflow_model: NA
  historical_outflow_model: NA
  future_outflow_model: NA
  local_inflow_directory: NA
  local_outflow_directory: NA
  use_flows_s3: NA
met:
  future_met_model: gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}
  historical_met_model: gefs-v12/stage3/site_id={site_id}
  historical_met_use_s3: no
  future_met_use_s3: no
  use_openmeteo: no
  local_met_directory: drivers/met
  use_forecasted_met: yes
  use_ler_vars: no
  forecast_lag_days: 1
uncertainty:
  use_obs_constraint: yes
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  met_downscale: yes
  inflow: yes
output_settings:
  diagnostics_names: extc
  evaluate_past: yes
  variables_in_scores:
  - state
  - parameter
  generate_plots: no
