s3:
  drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/ccre/lm_ar
  outflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/ccre/lm_ar
  targets:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/targets/ccre
  forecasts:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: ccre
  name: Carvins Cove Reservoir
  latitude: 37.3697
  longitude: -79.958
da_setup:
  da_method: enkf
  par_fit_method: perturb
  ensemble_size: 217
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: yes
  inflation_factor: 1.08
  localization_distance: .na
model_settings:
  ncore: 4
  model_name: glm
  base_GLM_nml: glm3_ccre.nml
  max_model_layers: 100
  modeled_depths:
  - 0.0
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  - 10.0
  - 12.0
  - 14.0
  - 16.0
  - 18.0
  - 20.0
  - 21.0
  par_config_file: parameter_calibration_config_ccre.csv
  obs_config_file: observations_config_ccre.csv
  states_config_file: states_config_ccre.csv
default_init:
  lake_depth: 22.8
  temp:
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  - 20
  temp_depths:
  - 0.1
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  - 10.0
  - 11.0
  - 15.0
  - 19.0
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
  include_inflow: no
  include_outflow: no
  historical_inflow_model: historical/model_id=historical_interp_inflow/site_id={site_id}
  future_inflow_model: future/model_id=inflow-aed/reference_date={reference_date}/site_id={site_id}
  historical_outflow_model: historical/model_id=historical_interp_outflow/site_id={site_id}
  future_outflow_model: future/model_id=outflow-aed/reference_date={reference_date}/site_id={site_id}
  local_inflow_directory: drivers/inflow
  local_outflow_directory: drivers/inflow
  use_flows_s3: no
  use_ler_vars: no
met:
  future_met_model: gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}
  historical_met_model: gefs-v12/stage3/site_id={site_id}
  historical_met_use_s3: no
  future_met_use_s3: no
  use_openmeteo: no
  local_met_directory: drivers/met
  use_forecasted_met: yes
  use_ler_vars: no
  forecast_lag_days: 1
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  met_downscale: yes
  inflow: yes
output_settings:
  diagnostics_names: extc
  generate_plots: no
